### ISSUE TITLE
Cannot provide output file for chaptertool convert commands

### ISSUE THREAD

**Issue by halkony** [Mtillmann/chaptertool#16]
Running the convert command with the `--output-file ./filename.json` flag leads to the following error:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received type boolean (true)
    at Object.openSync (node:fs:588:10)
    at writeFileSync (node:fs:2322:35)
    at new ChapterConverter (file:///C:/Users/halkony/.bun/install/global/node_modules/chaptertool/src/CLI/ChapterConverter.js:18:13)
    at file:///C:/Users/halkony/.bun/install/global/node_modules/chaptertool/chaptertool.js:26:9  
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:34:7)
    at async handleMainPromise (node:internal/modules/run_main:106:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

I confirmed that `options.outputFile` is being set to true inside of `chaptertool.js`, but the usage of `writeFileSync' in `ChapterConverter.js` expects a string.

I also noticed that the "--format" flag doesn't change the "outputFormat" option. I can change the value using `--outputFormat <format>` but similar to the earlier bug, it sets the option to true instead of the string value.

Tested on node 18 and 20.

**Comment by halkony** [comment]
Found the issue here. the `--output-file ./filename.json` argument should be `--output-file=./filename.json`. The format flag is "--outputFormat=<format key>".

**Comment by Mtillmann** [comment]
Hi, thanks for the heads up - I'll update the readme with the correct option name for the convert command.
